
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
