[tool.black]
line-length = 90
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
)/
'''

[build-system]
requires = ["cmake", "ninja", "scikit-build", "setuptools>=34.1.0", "wheel"]
