# flake8: noqa
from __future__ import absolute_import, division, print_function
from . import grabmodels
from . import randomforest
import utool
print, print_, printDBG, rrr, profile = utool.inject(
    __name__, '[detect]')

def reload_subs():
    """ Reloads detect and submodules """
    rrr()
    getattr(grabmodels, 'rrr', lambda: None)()
    getattr(randomforest, 'rrr', lambda: None)()
    rrr()
rrrr = reload_subs
# autogenerated __init__.py for: 'C:/Users/joncrall/code/ibeis/ibeis/model/detect'
