"""
AUTOGENERATED ON 16:27:22 2016/10/07
AutogenCommandLine:
    python -m ibeis.control.STAGING_SCHEMA --test-autogen_staging_schema --force-incremental-db-update --write
    python -m ibeis.control.STAGING_SCHEMA --test-autogen_staging_schema --force-incremental-db-update --diff=1
    python -m ibeis.control.STAGING_SCHEMA --test-autogen_staging_schema --force-incremental-db-update
"""
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals


# =======================
# Schema Version Current
# =======================


VERSION_CURRENT = '1.0.0'


def update_current(db, ibs=None):
    db.add_table('metadata', [
        ('metadata_rowid',               'INTEGER PRIMARY KEY'),
        ('metadata_key',                 'TEXT'),
        ('metadata_value',               'TEXT'),
    ],
        docstr='''
        The table that stores permanently all of the metadata about the
        database (tables, etc)
        ''',
        superkeys=[('metadata_key',)],
    )

    db.add_table('reviews', [
        ('review_rowid',                 'INTEGER PRIMARY KEY'),
        ('annot_1_rowid',                'INTEGER NOT NULL'),
        ('annot_2_rowid',                'INTEGER NOT NULL'),
        ('review_count',                 'INTEGER NOT NULL'),
        ('review_decision',              'INTEGER NOT NULL'),
        ('review_time_posix',            '''INTEGER DEFAULT (CAST(STRFTIME('%s', 'NOW', 'UTC') AS INTEGER))'''),  # this should probably be UCT
        ('review_identity',              'TEXT'),
        ('review_tags',                  'TEXT'),
    ],
        docstr='''
        Used to store completed user review states of two matched annotations
        ''',
        superkeys=[('annot_1_rowid', 'annot_2_rowid', 'review_count')],
    )
