# flake8: noqa
from __future__ import absolute_import, division, print_function

import utool as ut
ut.noinject(__name__, '[ibeis.model.preproc.__init__]', DEBUG=False)

from ibeis.model.preproc import preproc_chip
from ibeis.model.preproc import preproc_detectimg
from ibeis.model.preproc import preproc_encounter
from ibeis.model.preproc import preproc_feat
from ibeis.model.preproc import preproc_featweight
from ibeis.model.preproc import preproc_image
from ibeis.model.preproc import preproc_probchip
from ibeis.model.preproc import preproc_residual
from ibeis.model.preproc import preproc_rvec
import utool
print, print_, printDBG, rrr, profile = utool.inject(
    __name__, '[ibeis.model.preproc]')


def reload_subs(verbose=True):
    """ Reloads ibeis.model.preproc and submodules """
    rrr(verbose=verbose)
    def fbrrr(*args, **kwargs):
        """ fallback reload """
        pass
    getattr(preproc_annot, 'rrr', fbrrr)(verbose=verbose)
    getattr(preproc_chip, 'rrr', fbrrr)(verbose=verbose)
    getattr(preproc_detectchip, 'rrr', fbrrr)(verbose=verbose)
    getattr(preproc_detectimg, 'rrr', fbrrr)(verbose=verbose)
    getattr(preproc_encounter, 'rrr', fbrrr)(verbose=verbose)
    getattr(preproc_feat, 'rrr', fbrrr)(verbose=verbose)
    getattr(preproc_featweight, 'rrr', fbrrr)(verbose=verbose)
    getattr(preproc_image, 'rrr', fbrrr)(verbose=verbose)
    getattr(preproc_probchip, 'rrr', fbrrr)(verbose=verbose)
    getattr(preproc_residual, 'rrr', fbrrr)(verbose=verbose)
    getattr(preproc_rvec, 'rrr', fbrrr)(verbose=verbose)
    rrr(verbose=verbose)
rrrr = reload_subs

IMPORT_TUPLES = [
    ('preproc_annot', None),
    ('preproc_chip', None),
    ('preproc_detectchip', None),
    ('preproc_detectimg', None),
    ('preproc_encounter', None),
    ('preproc_feat', None),
    ('preproc_featweight', None),
    ('preproc_image', None),
    ('preproc_probchip', None),
    ('preproc_residual', None),
    ('preproc_rvec', None),
]

"""
Regen Command:
    cd /home/joncrall/code/ibeis/ibeis/model/preproc
    makeinit.py
"""
# autogenerated __init__.py for: '/home/joncrall/code/ibeis/ibeis/model/preproc'
