# flake8: noqa
from __future__ import absolute_import, division, print_function

import utool as ut
ut.noinject(__name__, '[ibeis.model.hots.smk.__init__]', DEBUG=False)

from . import smk_core
from . import smk_debug
from . import smk_index
from . import smk_match
from . import smk_plots
import utool
print, print_, printDBG, rrr, profile = utool.inject(__name__, '[smk]')

def reload_subs():
    """ Reloads smk and submodules """
    rrr()
    getattr(smk_core, 'rrr', lambda: None)()
    getattr(smk_debug, 'rrr', lambda: None)()
    getattr(smk_index, 'rrr', lambda: None)()
    getattr(smk_match, 'rrr', lambda: None)()
    getattr(smk_plots, 'rrr', lambda: None)()
    rrr()
rrrr = reload_subs
# autogenerated __init__.py for: 'C:/Users/joncrall/code/ibeis/ibeis/model/hots/smk'
