# package_manager, directory, update_schedule are required properties
# See https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    target_branch: "develop"
