# -*- coding: utf-8 -*-
# flake8: noqa
from __future__ import absolute_import, division, print_function

import utool as ut
ut.noinject(__name__, '[ibeis.algo.detect.__init__]')
from ibeis.algo.detect import grabmodels
from ibeis.algo.detect import randomforest
import utool as ut
print, rrr, profile = ut.inject2(
    __name__, '[ibeis.algo.detect]')


def reload_subs(verbose=True):
    """ Reloads ibeis.algo.detect and submodules """
    rrr(verbose=verbose)
    def fbrrr(*args, **kwargs):
        """ fallback reload """
        pass
    getattr(grabmodels, 'rrr', fbrrr)(verbose=verbose)
    getattr(randomforest, 'rrr', fbrrr)(verbose=verbose)
    rrr(verbose=verbose)
rrrr = reload_subs

IMPORT_TUPLES = [
    ('grabmodels', None),
    ('randomforest', None),
]

"""
Regen Command:
    cd /home/joncrall/code/ibeis/ibeis/algo/detect
    makeinit.py
"""
# autogenerated __init__.py for: '/home/joncrall/code/ibeis/ibeis/algo/detect'
